# This workflow checks a repository named KotlinWebSiteSnippetsTests scheduled, then creates an Issue if needed.

name: CI

# This part controls when the workflow will run.
on: 
[push]
  #schedule:
  # Here you can set any schedule of workflow execution
   # -cron: '0 6 * * *'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  schedule-check:
    name: Verifier run
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout verifier
      - uses: actions/checkout@v2
        with:
          repository: AlexanderPrendota/kotlin-samples-verifier
          ref: feature_commits
          path: verifier

      - name: Set up JDK 1.8
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
        
      - name: Grant execute permission for gradlew
        run: chmod +x ./verifier/gradlew
     
      - name: Build with Gradle
        working-directory: ./verifier
        run: |
             ./gradlew build -x test
             ./gradlew installDist
        
      - name: Run a docker with compiler-server
        working-directory: ./verifier
        run: ./gradlew dockerRun
     
      - name: Run verifier
        working-directory: ./verifier
        run: ./client/build/install/client/bin/client check -r https://github.com/kotushkens/kotlin-compiler-server -username ${{ secrets.TOKEN }} -path src/test/resources/test-compile-data/kotlin-web-site
      

